// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Abc: typeof import('./src/components/Abc.vue')['default']
    AStep: typeof import('ant-design-vue/es')['Step']
    ASteps: typeof import('ant-design-vue/es')['Steps']
    Header: typeof import('./src/components/header/index.vue')['default']
    Headers: typeof import('./src/components/Headers.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    JsMap: typeof import('./src/components/jsMap/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    Touch: typeof import('./src/components/touch/index.vue')['default']
    Undefined: typeof import('./src/components/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
  }
}
